userInput = input("Tell the cat what to say: ")
inputLength = len(userInput)
print(' ' * 11 + '_' * inputLength)
print(' ' * 9 + '< {} >'.format(userInput))
print(' ' * 11 + '_' * inputLength)
print(' ' * 9 + '/')
print(' /\_/\  /')
print('( o.o )')
print(' > ^ <')